# Generated by Django 5.0.4 on 2024-04-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='Bag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Men',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Shoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Watch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Women',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
