# Generated by Django 5.0.4 on 2024-04-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_category_product_bag_product_men_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Bag',
            new_name='bag',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Men',
            new_name='men',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Shoes',
            new_name='shoes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Watch',
            new_name='watch',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Women',
            new_name='women',
        ),
    ]
